package fr.mazure.simplellmtool.provider.custom.internal;

/**
 * Represents the actor (i.e. the source) of a message.
 * SYSTEM - Messages initiated by the system.
 * USER - Messages sent by the user.
 * MODEL - Responses generated by the model.
 */
enum Role {
    SYSTEM,
    USER,
    MODEL
}