package fr.mazure.simplellmtool.provider.custom.internal;

import java.util.List;

import fr.mazure.simplellmtool.tools.ToolParameterValue;

/**
 * Represents a round of message exchange.
 */
record MessageRound(Role role, String content, List<ToolCall> toolCalls, String tool, String toolCallId) {

    MessageRound(final Role role, final String content, List<ToolCall> toolCalls) {
        this(role, content, toolCalls, null, null);
    }

    MessageRound(final Role role, final String content) {
        this(role, content, List.of(), null, null);
    }

    MessageRound(final Role role, final String content, String tool, String toolCallId) {
        this(role, content, List.of(), tool, toolCallId);
    }

    /**
     * Represents the actor (i.e. the source) of a message.
     * SYSTEM - Messages initiated by the system.
     * USER - Messages sent by the user.
     * MODEL - Responses generated by the model.
     * TOOL - Results generated by a tool.
     */
    enum Role {
        SYSTEM,
        USER,
        MODEL,
        TOOL
    }

    /*
     * Represents a tool call in a round of message exchange
     */
    record ToolCall(String toolName, String toolCallId, List<ToolParameter> toolParameters) {
    }

    /*
     * Represents a parameter in a tool call in a round of message exchange
     */
    record ToolParameter(String parameterName, ToolParameterValue parameterValue) { // TODO the ToolParameterValue dependance is incorrect
    }
}
