package fr.mazure.simplellmtool.provider.custom.internal;

import java.util.List;

/**
 * Represents a round of message exchange.
 */
public record MessageRound(Role role, String content, List<ToolCall> toolCalls, String tool) {

    public MessageRound(final Role role, final String content, List<ToolCall> toolCalls) {
        this(role, content, toolCalls, null);
    }

    public MessageRound(final Role role, final String content) {
        this(role, content, List.of(), null);
    }

    public MessageRound(final Role role, final String content, String tool) {
        this(role, content, List.of(), tool);
    }

    /**
     * Represents the actor (i.e. the source) of a message.
     * SYSTEM - Messages initiated by the system.
     * USER - Messages sent by the user.
     * MODEL - Responses generated by the model.
     * TOOL - Results generated by a tool.
     */
    enum Role {
        SYSTEM,
        USER,
        MODEL,
        TOOL
    }

    /*
     * Represents a tool call in a round of message exchange
     */
    public record ToolCall(String toolName, List<ToolParameter> toolParameters) {
    }

    /*
     * Represents a paramteter in a tool call in a round of message exchange
     */
    public record ToolParameter(String parameterName, String parameterValue) {
    }
}
